#!/bin/sh

PATHTOCOMMON=/home/vagrant/os-challenge-common
SERVER=127.0.0.1
PORT=8080
SEED=1234
TOTAL=20
START=1
DIFFICULTY=10
REP_PROB_PERCENT=0
DELAY_US=100000
PRIO_LAMBDA=0

./client $SERVER $PORT $SEED $TOTAL $START $DIFFICULTY $REP_PROB_PERCENT $DELAY_US $PRIO_LAMBDA
